# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
# permalink:           pretty
permalink: /:year/:month/:day/:title/
##relative_permalinks: true

# Setup
title:               Doxanthropos
tagline:             'A personal weblog'
description:         'A blog about learning, coding and finding creative ways to do both.'
url:                 http://doxanthropos.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Knut Jackowski
  url:               https://twitter.com/doxanthropos
  email:             doxanthropos@gmail.com

# Custom vars
version:             1.0.0

gems:
  [jekyll-paginate]
