# Site settings
title: Doxanthropos
email: doxanthropos@gmail.com
author: Knut Jackowski
description: > # this means to ignore newlines until "baseurl:"
  A blog about learning, coding and finding creative ways to do both.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://doxanthropos.com" # the base hostname & protocol for your site
twitter_username: doxanthropos
github_username:  doxanthropos

# Build settings
markdown: kramdown

# permalink: pretty
permalink: /:year/:month/:day/:title/
